default:
    path_subject_1_raw:     "data-public/raw/subject-1.csv"
    path_mlm_1_raw:         "data-public/raw/mlm-1.csv"
    path_database:          "data-public/derived/mlm.sqlite3"
    path_county_derived:    "data-public/derived/county.rds"
    path_county_year_derived: "data-public/derived/county-year.rds"
    path_mlm_1_derived:     "data-public/derived/mlm-1.rds"

    path_annotation:        "data-public/raw/cqi-annotation.csv"
